server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2
spring:
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.database}?ssmode=allow
    username: ${postgres.username}
    password: ${postgres.password}
jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

# override prod configurations
postgres:
  url: 127.0.0.1:5432
  database: minipay_db
  username: admin
  password: 123