server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.database}?sslmode=allow

# override prod configurations
postgres:
  url: 127.0.0.1:5432
  database: minipay_db
  username: admin
  password: 123