server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/javascript,application/javascript,application/json
    min-response-size: 1024
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.database}?sslmode=Require;TrustServerCertificate=true
    username: ${postgres.username}
    password: ${postgres.password}

jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect