version: "3.7"

services:
  database:
    container_name: minipay_database
    image: postgres:16.3
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=minipay_db
    ports:
      - 5432:5432
    networks:
      - minipay_net

networks:
  minipay_net:
    driver: bridge